
FROM python:3.11-slim

WORKDIR /app
COPY orchestrator/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./orchestrator/app /app/app
COPY ./orchestrator/scripts /app/scripts
COPY ./shared /app/shared

ENV PYTHONPATH=/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "54321"]
