#!/bin/bash

# 🦁 SAAS BUILDER DEPLOYMENT SCRIPT (1000X)
# Autor: Huzeneger Omni-OS
# Descripción: Toma un proyecto generado por el Agente Coder y lo despliega en Docker localmente.

PROJECT_NAME=$1
PROJECT_PATH="./generated_saas/$PROJECT_NAME"

echo "🚀 [SAAS BUILDER] INICIANDO DESPLIEGUE AUTOMÁTICO: $PROJECT_NAME"

# 1. VALIDACIÓN
if [ -z "$PROJECT_NAME" ]; then
    echo "❌ Error: Debes especificar el nombre del proyecto."
    echo "Uso: ./deploy_saas.sh mi-nuevo-crm"
    exit 1
fi

if [ ! -d "$PROJECT_PATH" ]; then
    echo "⚠️  El proyecto no existe. Creando estructura base..."
    mkdir -p "$PROJECT_PATH"
    
    # Crear HTML básico de placeholder
    echo "<h1>🚀 $PROJECT_NAME IS LIVE!</h1><p>Generated by Huzeneger Omni-OS</p>" > "$PROJECT_PATH/index.html"
    
    # Crear Dockerfile básico (Nginx)
    echo "FROM nginx:alpine" > "$PROJECT_PATH/Dockerfile"
    echo "COPY . /usr/share/nginx/html" >> "$PROJECT_PATH/Dockerfile"
fi

# 2. CONSTRUCCIÓN DOCKER
echo "🏗️  Construyendo contenedor Docker..."
cd "$PROJECT_PATH" || exit
docker build -t "saas-$PROJECT_NAME" .

# 3. DESPLIEGUE
echo "⚡ Desplegando en puerto aleatorio (8000-9000)..."
PORT=$(shuf -i 8000-9000 -n 1)

# Detener si ya existe
docker rm -f "saas-$PROJECT_NAME" 2>/dev/null || true

# Correr
docker run -d --name "saas-$PROJECT_NAME" -p "$PORT:80" "saas-$PROJECT_NAME"

echo ""
echo "✅ SAAS DESPLEGADO CON ÉXITO!"
echo "🌐 URL: http://localhost:$PORT"
echo "📂 Path: $PROJECT_PATH"
echo "🦁 STATUS: ONLINE (Docker Container: saas-$PROJECT_NAME)"
